name: Publish Snapshot

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  publish:

    runs-on: macos-latest
    if: github.repository == 'freeletics/paparazzi'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11

      - name: Install Android SDK
        run: ./.github/android-sdk.sh

      - name: Set version for main
        if: ${{ github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "ORG_GRADLE_PROJECT_VERSION_NAME=main-SNAPSHOT" >> $GITHUB_ENV

      - name: Set version for branch
        if: ${{ github.ref_name != 'main' && !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "ORG_GRADLE_PROJECT_VERSION_NAME=${{ github.ref_name }}-SNAPSHOT" | sed 's#/#-#g' >> $GITHUB_ENV

      - uses: gradle/gradle-build-action@v2

      - name: Publish
        run: ./gradlew -p paparazzi publish
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.MAVEN_SIGNING_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.MAVEN_SIGNING_PASSWORD }}
        if: "${{ env.ORG_GRADLE_PROJECT_mavenCentralUsername != '' }}"
